name:                nfa-to-dfa
version:             0.1.0.0
github:              "czwinzscher/nfa-to-dfa"
license:             MIT
author:              "Clemens Zwinzscher"
copyright:           "2019 Clemens Zwinzscher"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/czwinzscher/nfa-to-dfa#readme>

dependencies:
- base

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Widentities
  - -Wredundant-constraints
  - -Wpartial-fields
  - -Wcompat
  - -Wunused-packages

library:
  source-dirs: src
  dependencies:
    - aeson
    - aeson-casing
    - containers

executables:
  nfa-to-dfa:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nfa-to-dfa
    - aeson
    - bytestring
    - optparse-applicative

tests:
  nfa-to-dfa-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - nfa-to-dfa
    - containers
    - tasty
    - tasty-hunit
