name: CI

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  stack:
    name: stack latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: haskell/actions/setup@v1
        name: setup stack
        with:
          enable-stack: true
          stack-no-global: true
          stack-version: 'latest'

      - uses: actions/cache@v1
        name: cache ~/.stack
        with:
          path: ~/.stack
          key: ${{ runner.os }}-stack-${{ hashFiles('**.yaml') }}

      - name: build
        run: |
          stack build

      - name: test
        run: |
          stack test
